"""Seed data: FedCompass modules, algorithms, references, datasets."""
from app.models.models import (
    Module, Algorithm, ModuleAlgorithm,
    ReferenceAsset, ModuleReference, AlgorithmReference,
    Dataset,
    AssetType, ImplementationStatus,
)


MODULES = [
    {
        "id": "core_engine", "name": "训练编排核心",
        "positioning": "联邦训练核心循环与状态管理",
        "description": "实现 Server/Client/Trainer/Registry 的核心编排。支持基础联邦算法库和统一训练循环。",
        "capabilities": ["server_client_loop", "state_management", "registry"],
        "primary_algorithms": ["fedavg", "fedprox", "scaffold", "feddyn", "fednova", "fedadam", "fedyogi", "fedbn", "ditto", "pfedme", "fedproto", "feddf", "fedkd"],
        "baseline_algorithms": [],
        "status": ImplementationStatus.implemented,
        "meta_json": {"implementation_status": "implemented", "problem_focus": "实现 Server/Client/Trainer/Registry 的核心编排", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["总览", "模块能力", "运行监控"], "showcase_points": ["Server、Client、Trainer、StateStore、Registry 的训练流程图", "核心训练循环与状态流转说明"], "backend_service": "Core Orchestration Service", "config_fields": ["task_type", "rounds", "local_epochs", "num_clients", "seed"], "backend_plugins": ["core/server.py", "core/client.py", "core/trainer.py"]},
    },
    {
        "id": "participation_adaptation", "name": "低参与异构适配",
        "positioning": "低参与率与异构感知补偿",
        "description": "聚焦 Non-IID、silence table、EMA 异质性与梯度漂移修正。支持 FedCVC、FedDTC、RFL-NLCP。",
        "capabilities": ["heterogeneity", "low_participation", "drift_compensation"],
        "primary_algorithms": ["fedcvc", "feddtc", "rfl_nlcp"],
        "baseline_algorithms": ["fedavg", "fedprox", "scaffold", "feddyn", "a_fedpd", "feddc", "fedvra", "fedvarp", "fedspeed", "fedsmoo", "fedtoga", "gfed_hsam"],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "聚焦 Non-IID、silence table、EMA 异质性与梯度漂移修正", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["模块能力", "实验配置", "运行监控"], "showcase_points": ["Non-IID、低参与率、silence table、EMA 异质性、梯度漂移补偿", "低参与异构场景下的漂移修正思路"], "backend_service": "Adaptation Strategy Service", "config_fields": ["split", "participation_rate", "silence_rate", "learning_rate"], "backend_plugins": ["plugins/algorithms/fedcvc.py", "plugins/algorithms/feddtc.py"]},
    },
    {
        "id": "optimization_control", "name": "联邦优化控制",
        "positioning": "优化器与 sharpness-aware 约束",
        "description": "支持 SAM/ESAM/HSAM 与 GFed-HSAM。对比 FedCVC、FedDyn、FedProx、SCAFFOLD、SAM/ESAM/HSAM 优化策略。",
        "capabilities": ["sharpness_aware", "regularization", "optimization"],
        "primary_algorithms": ["gfed_hsam", "sam", "esam", "hsam"],
        "baseline_algorithms": ["fedavg", "feddyn", "fedprox", "scaffold", "a_fedpd", "fedspeed", "fedsmoo", "fedlesam_d", "a_fedpdsam", "fedgloss", "fedvra", "fedvarp", "fedtoga"],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "支持 SAM/ESAM/HSAM 与 GFed-HSAM", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["模块能力", "实验配置"], "showcase_points": ["FedCVC、GFed-HSAM、FedDyn、FedProx、SCAFFOLD、SAM/ESAM/HSAM 对比", "优化器选择与 sharpness-aware 约束示意"], "backend_service": "Optimizer Control Service", "config_fields": ["optimizer", "learning_rate", "batch_size"], "backend_plugins": ["plugins/optimizers/sam.py", "plugins/optimizers/hsam.py"]},
    },
    {
        "id": "distillation_alignment", "name": "蒸馏对齐增强",
        "positioning": "蒸馏与特征对齐增强",
        "description": "接入 self/global dual distillation 与动态蒸馏权重。self/global dual distillation、动态蒸馏权重、特征对齐。",
        "capabilities": ["knowledge_distillation", "feature_alignment", "participation_aware"],
        "primary_algorithms": ["fedcads"],
        "baseline_algorithms": ["fedavg", "feddyn", "scaffold", "feddc", "fedvra", "fedgkd_p", "a_fedpd", "fedfld"],
        "status": ImplementationStatus.implemented,
        "meta_json": {"implementation_status": "implemented", "problem_focus": "接入 self/global dual distillation 与动态蒸馏权重", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["模块能力", "实验配置"], "showcase_points": ["self/global dual distillation、动态蒸馏权重、特征对齐", "蒸馏分支与表征对齐关系图"], "backend_service": "Distillation Alignment Service", "config_fields": ["algorithm", "distill_weight", "global_distill_weight", "temperature"], "backend_plugins": ["plugins/algorithms/fedcads.py"]},
    },
    {
        "id": "robust_aggregation", "name": "鲁棒聚合防护",
        "positioning": "聚合前鲁棒防御筛选",
        "description": "支持 VERT、Krum、Median、Trimmed Mean、FLDetector。VERT、Krum、Median、Trimmed Mean、FLDetector 和攻击模拟。",
        "capabilities": ["byzantine_defense", "aggregation", "attack_detection"],
        "primary_algorithms": ["vert", "krum", "median", "trimmed_mean", "fldetector"],
        "baseline_algorithms": ["fedavg", "fltrust", "flame", "multi_krum"],
        "status": ImplementationStatus.validated,
        "meta_json": {"implementation_status": "validated", "problem_focus": "支持 VERT、Krum、Median、Trimmed Mean、FLDetector", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["总览", "模块能力", "运行监控"], "showcase_points": ["VERT、Krum、Median、Trimmed Mean、FLDetector 和攻击模拟", "可信客户端筛选与聚合前防护示意"], "backend_service": "Robust Defense Service", "config_fields": ["defense", "attack", "trust_threshold"], "backend_plugins": ["plugins/defenses/vert.py"]},
    },
    {
        "id": "trust_screening", "name": "可信客户端筛选",
        "positioning": "轻量可信客户端筛选",
        "description": "历史梯度几何一致性与低开销防御。历史梯度几何一致性、可信客户端筛选、低开销防御。",
        "capabilities": ["lightweight_defense", "geometric_consistency", "client_filtering"],
        "primary_algorithms": ["flbeeline"],
        "baseline_algorithms": ["fedavg", "krum", "multi_krum", "median", "flame", "fltrust"],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "历史梯度几何一致性与低开销防御", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["模块能力", "运行监控"], "showcase_points": ["历史梯度几何一致性、可信客户端筛选、低开销防御", "Top-K 可信客户端筛选示意"], "backend_service": "Trust Screening Service", "config_fields": ["defense", "participation_rate", "trust_threshold"], "backend_plugins": ["code1/defenses.py"]},
    },
    {
        "id": "representation_attack", "name": "特征投毒分析",
        "positioning": "特征层投毒攻击展示",
        "description": "聚焦 prototype poisoning 与表征异常检测。特征层投毒、原型投毒、FedProto 风格攻击与异常原型检测。",
        "capabilities": ["featurepoison", "prototype_attack", "anomaly_detection"],
        "primary_algorithms": ["featurepoison", "fedproto_prototype_attack"],
        "baseline_algorithms": [],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "聚焦 prototype poisoning 与表征异常检测", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["模块能力", "实验配置"], "showcase_points": ["特征层投毒、原型异常检测、表征安全", "prototype poisoning 与异常表征检测示意"], "backend_service": "Representation Security Service", "config_fields": ["attack", "defense", "split"], "backend_plugins": ["exps/federated_main.py", "lib/update.py"]},
    },
    {
        "id": "vision_benchmark", "name": "视觉分类基准",
        "positioning": "视觉分类基准任务",
        "description": "支持 CIFAR/MNIST/Tiny-ImageNet 的联邦视觉实验展示。CIFAR-10、CIFAR-100、MNIST、Tiny-ImageNet 基准，支持 IID/Dirichlet/Pathological 划分。",
        "capabilities": ["vision_classification", "heterogeneous_split", "benchmark"],
        "primary_algorithms": ["fedavg", "feddyn", "fedcads", "rfl_nlcp", "fedcvc", "feddtc", "gfed_hsam"],
        "baseline_algorithms": ["fedavg", "fedprox", "scaffold", "feddyn", "feddc", "fedvra", "fedvarp", "fedgkd_p", "a_fedpd", "fedfld", "fedspeed", "fedsmoo", "fedtoga"],
        "status": ImplementationStatus.implemented,
        "meta_json": {"implementation_status": "implemented", "problem_focus": "支持 CIFAR/MNIST/Tiny-ImageNet 的联邦视觉实验展示", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["总览", "应用场景", "结果对比"], "showcase_points": ["CIFAR/MNIST/Tiny-ImageNet、IID/Dirichlet/Pathological split", "分类任务样例与基础算法对比"], "backend_service": "Vision Benchmark Service", "config_fields": ["dataset", "split", "algorithm"], "backend_plugins": ["plugins/apps/vision"]},
    },
    {
        "id": "reid_generalization", "name": "ReID 域泛化应用",
        "positioning": "域泛化 ReID 应用页",
        "description": "展示 CO-EVO 的 semantic anchor 与 style bank。CO-EVO：联合演化语义锚定与风格多样化，mAP/Rank-1 评测。",
        "capabilities": ["reid", "domain_generalization", "semantic_anchor"],
        "primary_algorithms": ["co_evo"],
        "baseline_algorithms": ["scaffold", "moon", "fedprox", "mixstyle", "crossstyle", "fedreid", "fedpav", "snr", "dacs", "sscu"],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "展示 CO-EVO 的 semantic anchor 与 style bank", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["应用场景", "结果对比"], "showcase_points": ["CO-EVO、semantic anchor、global style bank、mAP/Rank-1", "ReID 域泛化机制与指标对比"], "backend_service": "ReID Generalization Service", "config_fields": ["dataset", "algorithm", "rounds"], "backend_plugins": ["plugins/apps/reid/co_evo.py"]},
    },
    {
        "id": "multimodal_3d", "name": "3D 多模态应用",
        "positioning": "3D 多模态应用页",
        "description": "展示 FedULIP base-to-new 与 cross-dataset 结果。FedULIP：点云/文本/图像多模态联邦学习。",
        "capabilities": ["3d_multimodal", "point_cloud", "cross_dataset"],
        "primary_algorithms": ["fedulip"],
        "baseline_algorithms": ["fedavg", "ulip", "pointclip", "fedkgcoop", "fedvpt", "fedtpg", "fedcocoop", "fedmaple", "fedclip", "fedmvp"],
        "status": ImplementationStatus.mocked,
        "meta_json": {"implementation_status": "mocked", "problem_focus": "展示 FedULIP base-to-new 与 cross-dataset 结果", "io_contract": "输入为实验配置、客户端状态与算法参数；输出为模型更新、指标、日志与结果摘要。", "frontend_views": ["应用场景", "结果对比"], "showcase_points": ["FedULIP、ULIP backbone、adapter/SACA、跨数据集评测", "base-to-new/cross-dataset/domain ABCD 评测协议"], "backend_service": "3D Multimodal Service", "config_fields": ["dataset", "algorithm", "task_type"], "backend_plugins": ["plugins/apps/ulip3d/fedulip.py"]},
    },
    {
        "id": "experiment_toolkit", "name": "实验配置与结果工具",
        "positioning": "配置、日志与结果导出工具",
        "description": "负责配置预览、实验模板、导出与结果复现。实验模板、日志解析、结果导出、批量任务管理。",
        "capabilities": ["config", "logging", "export", "batch"],
        "primary_algorithms": [],
        "baseline_algorithms": [],
        "status": ImplementationStatus.implemented,
        "meta_json": {"implementation_status": "implemented", "problem_focus": "负责配置预览、实验模板、导出与结果复现", "io_contract": "输入为实验配置；输出为配置文件、日志、导出结果。", "frontend_views": ["总览", "实验配置", "结果对比"], "showcase_points": ["配置、日志、checkpoint、结果表格、批量任务", "实验模板、导出与结果复现工具链"], "backend_service": "Experiment Utility Service", "config_fields": ["seed", "export_format", "template_id"], "backend_plugins": ["configs/", "outputs/", "scripts/"]},
    },
]


ALGORITHMS = [
    # -- Core aggregation --
    {"id": "fedavg", "name": "FedAvg", "category": "aggregation", "description": "Federated Averaging 基线算法。通信高效的联邦学习标准算法。", "task_types": ["vision_classification", "reid", "ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.implemented},
    {"id": "feddyn", "name": "FedDyn", "category": "regularization", "description": "动态正则化联邦学习。通过历史梯度累积实现动态正则化。", "task_types": ["vision_classification"], "parameter_schema": {"alpha": {"type": "number", "default": 0.01}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},
    {"id": "fedprox", "name": "FedProx", "category": "regularization", "description": "近端项联邦学习。引入近端项约束处理异构客户端。", "task_types": ["vision_classification"], "parameter_schema": {"mu": {"type": "number", "default": 0.01}}, "hooks": ["before_local_train"], "status": ImplementationStatus.mocked},
    {"id": "scaffold", "name": "SCAFFOLD", "category": "correction", "description": "梯度校正联邦学习。使用控制变量校正客户端漂移。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": ["before_local_train", "after_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "fednova", "name": "FedNova", "category": "aggregation", "description": "归一化联邦平均，缓解本地步数异构导致的目标不一致。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},
    {"id": "fedadam", "name": "FedAdam", "category": "server_optimizer", "description": "FedOpt 系列自适应服务端优化基线，使用 Adam 风格动量更新。", "task_types": ["vision_classification"], "parameter_schema": {"server_lr": {"type": "number", "default": 0.04}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},
    {"id": "fedyogi", "name": "FedYogi", "category": "server_optimizer", "description": "FedOpt 系列 Yogi 服务端自适应优化基线。", "task_types": ["vision_classification"], "parameter_schema": {"server_lr": {"type": "number", "default": 0.03}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},
    {"id": "fedbn", "name": "FedBN", "category": "normalization", "description": "本地 BatchNorm 个性化基线，用于特征偏移和跨域 Non-IID 场景。", "task_types": ["vision_classification", "reid"], "parameter_schema": {}, "hooks": ["before_local_train"], "status": ImplementationStatus.implemented},
    {"id": "ditto", "name": "Ditto", "category": "personalization", "description": "个性化联邦学习基线，同时维护全局模型与客户端个性模型。", "task_types": ["vision_classification", "reid"], "parameter_schema": {"personalization_weight": {"type": "number", "default": 0.3}}, "hooks": ["before_local_train"], "status": ImplementationStatus.implemented},
    {"id": "pfedme", "name": "pFedMe", "category": "personalization", "description": "Moreau envelope 个性化联邦学习基线。", "task_types": ["vision_classification", "reid"], "parameter_schema": {"moreau_mu": {"type": "number", "default": 0.05}}, "hooks": ["before_local_train"], "status": ImplementationStatus.implemented},
    {"id": "fedproto", "name": "FedProto", "category": "prototype", "description": "跨客户端原型聚合基线，适合特征原型和个性化场景。", "task_types": ["vision_classification", "reid"], "parameter_schema": {}, "hooks": ["before_aggregate", "after_local_train"], "status": ImplementationStatus.implemented},
    {"id": "feddf", "name": "FedDF", "category": "distillation", "description": "服务端集成蒸馏联邦融合基线。", "task_types": ["vision_classification"], "parameter_schema": {"distill_weight": {"type": "number", "default": 0.4}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},
    {"id": "fedkd", "name": "FedKD", "category": "distillation", "description": "知识蒸馏式通信高效联邦学习基线。", "task_types": ["vision_classification"], "parameter_schema": {"distill_weight": {"type": "number", "default": 0.4}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.implemented},

    # -- Participation adaptation --
    {"id": "fedcvc", "name": "FedCVC", "category": "compensation", "description": "Client-Driven Virtual Compensation for Mitigating Dual Drift。客户端驱动的虚拟补偿缓解双重漂移。", "task_types": ["vision_classification"], "parameter_schema": {"dual_lr": {"type": "number", "default": 0.01}, "compensation_weight": {"type": "number", "default": 1.0}, "silence_window": {"type": "integer", "default": 5}}, "hooks": ["before_aggregate", "after_local_train", "update_global_state"], "status": ImplementationStatus.mocked},
    {"id": "feddtc", "name": "FedDTC", "category": "compensation", "description": "动态异质性感知与全局梯度偏移校正。基于 EMA 的异质性追踪与偏移补偿。", "task_types": ["vision_classification"], "parameter_schema": {"ema_alpha": {"type": "number", "default": 0.9}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "rfl_nlcp", "name": "RFL-NLCP", "category": "robust", "description": "Robust FL with non-IID Data and Limited Client Participation。非IID数据与有限客户端参与下的鲁棒联邦学习。", "task_types": ["vision_classification"], "parameter_schema": {"robust_threshold": {"type": "number", "default": 0.5}}, "hooks": ["before_aggregate", "client_filter"], "status": ImplementationStatus.mocked},

    # -- Optimization control --
    {"id": "gfed_hsam", "name": "GFed-HSAM", "category": "optimization", "description": "General Dynamic Regularization FL with Hybrid Sharpness-Aware Minimization。混合锐度感知最小化的联邦优化。", "task_types": ["vision_classification"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}}, "hooks": ["before_local_train", "after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "sam", "name": "SAM", "category": "optimizer", "description": "Sharpness-Aware Minimization 优化器。通过寻找最陡方向提升泛化性能。", "task_types": ["vision_classification", "reid", "ulip3d"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}}, "hooks": ["before_local_train"], "status": ImplementationStatus.implemented},
    {"id": "esam", "name": "ESAM", "category": "optimizer", "description": "Efficient SAM 优化器。在 SAM 基础上引入动量提升计算效率。", "task_types": ["vision_classification", "reid", "ulip3d"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}, "beta": {"type": "number", "default": 0.9}}, "hooks": ["before_local_train"], "status": ImplementationStatus.mocked},
    {"id": "hsam", "name": "HSAM", "category": "optimizer", "description": "Hybrid SAM 优化器。多扰动采样的混合锐度感知优化。", "task_types": ["vision_classification", "reid", "ulip3d"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}, "num_samples": {"type": "integer", "default": 3}}, "hooks": ["before_local_train"], "status": ImplementationStatus.mocked},

    # -- Distillation --
    {"id": "fedcads", "name": "FedCADS", "category": "distillation", "description": "Robust FL via Dual Distillation and Participation-Aware Optimization。双蒸馏与参与感知优化的鲁棒联邦学习。", "task_types": ["vision_classification"], "parameter_schema": {"distill_weight": {"type": "number", "default": 0.5}, "self_distill": {"type": "boolean", "default": True}}, "hooks": ["before_aggregate", "after_local_train"], "status": ImplementationStatus.implemented},

    # -- Paper baseline algorithms for FL optimization and non-IID protocols --
    {"id": "a_fedpd", "name": "A-FedPD", "category": "fl_baseline", "description": "Accelerated Federated Primal-Dual baseline used in FedCVC/FedCADS comparisons。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "a_fedpdsam", "name": "A-FedPDSAM", "category": "sam_fl_baseline", "description": "A-FedPD with sharpness-aware minimization, used as a SAM-based FedCVC baseline。", "task_types": ["vision_classification"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedspeed", "name": "FedSpeed", "category": "sam_fl_baseline", "description": "SAM-style federated optimization baseline for non-IID and limited-participation comparisons。", "task_types": ["vision_classification"], "parameter_schema": {"rho": {"type": "number", "default": 0.05}}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedsmoo", "name": "FedSMOO", "category": "sam_fl_baseline", "description": "Federated smooth optimization baseline referenced by FedCVC/RFL-NLCP。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedlesam_d", "name": "FedLESAM-D", "category": "sam_fl_baseline", "description": "Local-efficient SAM baseline in FedCVC's SAM-based comparison suite。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedgloss", "name": "FedGLOSS", "category": "sam_fl_baseline", "description": "Global-local sharpness-aware optimization baseline used for FedCVC comparison。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "feddc", "name": "FedDC", "category": "non_iid_baseline", "description": "Federated drift decoupling/correction baseline for non-IID data。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedvra", "name": "FedVRA", "category": "non_iid_baseline", "description": "Variance-reduction/adaptation baseline appearing in FedCADS and RFL-NLCP comparisons。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedvarp", "name": "FedVARP", "category": "non_iid_baseline", "description": "Variance-reduced primal baseline used in RFL-NLCP comparisons。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedtoga", "name": "FedTOGA", "category": "non_iid_baseline", "description": "Gradient/optimization adjustment baseline used by RFL-NLCP。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedgkd_p", "name": "FedGKD-P", "category": "distillation_baseline", "description": "Global knowledge distillation baseline from FedCADS comparisons。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedfld", "name": "FedFLD", "category": "distillation_baseline", "description": "Feature/logit distillation baseline used in FedCADS comparisons。", "task_types": ["vision_classification"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},

    # -- Defenses --
    {"id": "vert", "name": "VERT", "category": "defense", "description": "Vertical solution against large-scale model poisoning。垂直防御方案，基于信任评分与客户端过滤。", "task_types": ["defense_demo", "vision_classification"], "parameter_schema": {"threshold": {"type": "number", "default": 0.8}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "krum", "name": "Krum", "category": "defense", "description": "Byzantine-robust Krum 聚合。选择最接近多数客户端的更新。", "task_types": ["defense_demo"], "parameter_schema": {"num_to_keep": {"type": "integer", "default": 1}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "median", "name": "Median", "category": "defense", "description": "Coordinate-wise Median 聚合。对每个坐标维度取中位数。", "task_types": ["defense_demo"], "parameter_schema": {}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "trimmed_mean", "name": "Trimmed Mean", "category": "defense", "description": "Trimmed Mean 鲁棒聚合。去除极值后取均值。", "task_types": ["defense_demo"], "parameter_schema": {"trim_ratio": {"type": "number", "default": 0.1}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "fldetector", "name": "FLDetector", "category": "defense", "description": "恶意客户端检测。基于模型更新一致性检测恶意客户端。", "task_types": ["defense_demo"], "parameter_schema": {}, "hooks": ["before_aggregate"], "status": ImplementationStatus.mocked},
    {"id": "flbeeline", "name": "FLBeeline", "category": "defense", "description": "Lightweight large-scale model poisoning defense。轻量级大规模投毒防御，基于历史梯度几何一致性。", "task_types": ["defense_demo", "vision_classification"], "parameter_schema": {"top_k": {"type": "integer", "default": 10}}, "hooks": ["before_aggregate", "client_filter"], "status": ImplementationStatus.mocked},
    {"id": "multi_krum", "name": "Multi-Krum", "category": "defense", "description": "Krum 的多更新选择版本，常用于拜占庭鲁棒聚合对照。", "task_types": ["defense_demo"], "parameter_schema": {"num_to_keep": {"type": "integer", "default": 5}}, "hooks": ["before_aggregate"], "status": ImplementationStatus.paper_only},
    {"id": "fltrust", "name": "FLTrust", "category": "defense", "description": "使用可信根数据校准客户端更新的鲁棒联邦防御基线。", "task_types": ["defense_demo", "vision_classification"], "parameter_schema": {}, "hooks": ["before_aggregate"], "status": ImplementationStatus.paper_only},
    {"id": "flame", "name": "FLAME", "category": "defense", "description": "面向模型投毒的聚类与裁剪防御基线。", "task_types": ["defense_demo"], "parameter_schema": {}, "hooks": ["before_aggregate"], "status": ImplementationStatus.paper_only},

    # -- Attacks --
    {"id": "featurepoison", "name": "FeaturePoison", "category": "attack", "description": "Feature-level poisoning attack。特征层级投毒攻击，操纵原型表征。", "task_types": ["defense_demo", "vision_classification"], "parameter_schema": {"poison_ratio": {"type": "number", "default": 0.2}}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "fedproto_prototype_attack", "name": "FedProto Prototype Attack", "category": "attack", "description": "Prototype poisoning under FedProto framework。FedProto 框架下的原型投毒攻击。", "task_types": ["defense_demo"], "parameter_schema": {}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},

    # -- Apps --
    {"id": "sgd", "name": "SGD", "category": "optimizer", "description": "标准随机梯度下降优化器。", "task_types": ["vision_classification", "reid", "ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.implemented},
    {"id": "gn", "name": "GN", "category": "attack", "description": "Gaussian Noise：向模型更新注入高斯噪声。", "task_types": ["defense_demo"], "parameter_schema": {"noise_scale": {"type": "number", "default": 1.0}}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "mr", "name": "MR", "category": "attack", "description": "Model Replacement：用恶意模型替换正常更新。", "task_types": ["defense_demo"], "parameter_schema": {"scale_factor": {"type": "number", "default": 10.0}}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "agr", "name": "AGR", "category": "attack", "description": "AGR Byzantine：针对聚合机制的拜占庭攻击。", "task_types": ["defense_demo"], "parameter_schema": {}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "alie", "name": "ALIE", "category": "attack", "description": "A Little Is Enough：微小扰动破坏聚合。", "task_types": ["defense_demo"], "parameter_schema": {"z_max": {"type": "number", "default": 1.5}}, "hooks": ["after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "co_evo", "name": "CO-EVO", "category": "reid", "description": "Co-evolving Semantic Anchoring and Style Diversification for Federated DG-ReID。联合演化语义锚定与风格多样化。", "task_types": ["reid"], "parameter_schema": {"lambda_anchor": {"type": "number", "default": 1.0}, "lambda_style": {"type": "number", "default": 0.1}}, "hooks": ["before_local_train", "after_local_train"], "status": ImplementationStatus.mocked},
    {"id": "fedulip", "name": "FedULIP", "category": "3d_multimodal", "description": "Federated ULIP for 3D multimodal learning。点云/文本/图像多模态联邦学习。", "task_types": ["ulip3d"], "parameter_schema": {"adapter_type": {"type": "string", "default": "saca"}}, "hooks": ["before_local_train"], "status": ImplementationStatus.mocked},
    {"id": "moon", "name": "MOON", "category": "reid_baseline", "description": "Model-contrastive federated learning baseline used in CO-EVO comparisons。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "mixstyle", "name": "MixStyle", "category": "domain_generalization", "description": "Feature statistics mixing baseline for domain generalization ReID。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "crossstyle", "name": "CrossStyle", "category": "domain_generalization", "description": "Cross-domain style augmentation baseline for ReID domain generalization。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedreid", "name": "FedReID", "category": "reid_baseline", "description": "Federated person ReID baseline used by CO-EVO。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedpav", "name": "FedPav", "category": "reid_baseline", "description": "Federated ReID baseline from the CO-EVO evaluation suite。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "snr", "name": "SNR", "category": "domain_generalization", "description": "Style normalization/restoration domain generalization baseline for ReID。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "dacs", "name": "DACS", "category": "domain_generalization", "description": "Domain-adaptive/cross-style baseline used in CO-EVO comparisons。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "sscu", "name": "SSCU", "category": "domain_generalization", "description": "Self-supervised/cross-domain ReID baseline in the CO-EVO comparison suite。", "task_types": ["reid"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "ulip", "name": "ULIP", "category": "3d_pretraining_baseline", "description": "Unified language-image-point representation baseline for 3D understanding。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "pointclip", "name": "PointCLIP", "category": "3d_prompt_baseline", "description": "CLIP-based point cloud recognition baseline referenced by FedULIP。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedkgcoop", "name": "FedKgCoOp", "category": "3d_prompt_baseline", "description": "Federated prompt-learning baseline used in FedULIP comparisons。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedvpt", "name": "FedVPT", "category": "3d_prompt_baseline", "description": "Federated visual prompt tuning baseline for 3D multimodal experiments。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedtpg", "name": "FedTPG", "category": "3d_prompt_baseline", "description": "Federated text prompt generation baseline from FedULIP comparisons。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedcocoop", "name": "FedCoCoOp", "category": "3d_prompt_baseline", "description": "Federated conditional prompt-learning baseline for multimodal transfer。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedmaple", "name": "FedMaPLe", "category": "3d_prompt_baseline", "description": "Federated multi-modal prompt learning baseline in FedULIP。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedclip", "name": "FedCLIP", "category": "3d_prompt_baseline", "description": "Federated CLIP adaptation baseline for 3D multimodal evaluation。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
    {"id": "fedmvp", "name": "FedMVP", "category": "3d_prompt_baseline", "description": "Federated multi-view prompt baseline used in FedULIP comparisons。", "task_types": ["ulip3d"], "parameter_schema": {}, "hooks": [], "status": ImplementationStatus.paper_only},
]


REFERENCES = [
    {"id": "paper_fedavg", "asset_type": AssetType.paper, "title": "Communication-Efficient Learning of Deep Networks from Decentralized Data (FedAvg)", "local_path": "FedAvg-1602.05629v4.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fednova", "asset_type": AssetType.paper, "title": "FedNova: Tackling Objective Inconsistency in Heterogeneous Federated Optimization", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedopt", "asset_type": AssetType.paper, "title": "Adaptive Federated Optimization (FedOpt/FedAdam/FedYogi)", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedbn", "asset_type": AssetType.paper, "title": "FedBN: Federated Learning on Non-IID Features via Local Batch Normalization", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_ditto", "asset_type": AssetType.paper, "title": "Ditto: Fair and Robust Federated Learning Through Personalization", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_pfedme", "asset_type": AssetType.paper, "title": "pFedMe: Personalized Federated Learning with Moreau Envelopes", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedproto", "asset_type": AssetType.paper, "title": "FedProto: Federated Prototype Learning across Heterogeneous Clients", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_feddf", "asset_type": AssetType.paper, "title": "FedDF: Ensemble Distillation for Robust Model Fusion in Federated Learning", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedkd", "asset_type": AssetType.paper, "title": "Federated Knowledge Distillation Baseline", "local_path": None, "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedcvc_2026", "asset_type": AssetType.paper, "title": "FedCVC: Federated Primal-Dual Learning with Client-Driven Virtual Compensation", "local_path": "Lai_FedCVC_Federated_Primal-Dual_Learning_with_Client-Driven_Virtual_Compensation_for_Mitigating_CVPRF_2026_paper.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedcads", "asset_type": AssetType.paper, "title": "FEDCADS: Robust Federated Learning via Dual Distillation and Participation-Aware Optimization Under non-IID Data", "local_path": "FedCADS.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_rfl_nlcp", "asset_type": AssetType.paper, "title": "RFL-NLCP: Robust Federated Learning with non-IID Data and Limited Client Participation", "local_path": "RFL-NLCP.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_gfed_hsam", "asset_type": AssetType.paper, "title": "General Dynamic Regularization Federated Learning with Hybrid Sharpness-Aware Minimization", "local_path": "General_Dynamic_Regularization_Federated_Learning_with_Hybrid_Sharpness-Aware_Minimization (1).pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_feddtc", "asset_type": AssetType.paper, "title": "基于动态异质性感知与全局梯度偏移校正的联邦对偶优化算法研究", "local_path": "基于动态异质性感知与全局梯度偏移校正的联邦对偶优化算法研究-小微格式.docx", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_sam", "asset_type": AssetType.paper, "title": "Sharpness-Aware Minimization for Efficiently Improving Generalization (SAM)", "local_path": "SAM-2010.01412v3.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_esam", "asset_type": AssetType.paper, "title": "Efficient Sharpness-Aware Minimization (ESAM)", "local_path": "ESAM.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_vert", "asset_type": AssetType.paper, "title": "How to Defend Against Large-Scale Model Poisoning Attacks in Federated Learning: A Vertical Solution", "local_path": "How_to_Defend_Against_Large-Scale_Model_Poisoning_Attacks_in_Federated_Learning_A_Vertical_Solution.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_krum", "asset_type": AssetType.paper, "title": "Machine Learning with Adversaries: Byzantine-Tolerant Gradient Descent (Krum)", "local_path": "Krum-NIPS-2017-machine-learning-with-adversaries-byzantine-tolerant-gradient-descent-Paper.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_median", "asset_type": AssetType.paper, "title": "Byzantine-Robust Distributed Learning: Towards Optimal Statistical Rates (Median/Trimmed Mean)", "local_path": "Mean.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fldetector", "asset_type": AssetType.paper, "title": "FLDetector: Defending Federated Learning Against Model Poisoning Attacks", "local_path": "FLDetector-2207.09209v4.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_flbeeline", "asset_type": AssetType.paper, "title": "FLBeeline：轻量级大规模投毒防御", "local_path": "软件学报1.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_co_evo", "asset_type": AssetType.paper, "title": "CO-EVO: Co-evolving Semantic Anchoring and Style Diversification for Federated DG-ReID", "local_path": "CO-EVO-2604.26363v1.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_fedulip", "asset_type": AssetType.paper, "title": "FedULIP: Federated Prompt Learning for 3D Multimodal Understanding", "local_path": "FedULIP.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "paper_ulip", "asset_type": AssetType.paper, "title": "ULIP: Learning a Unified Representation of Language, Images, and Point Clouds for 3D Understanding", "local_path": "ULIP-2212.05171v4.pdf", "external_url": None, "default_branch": None, "key_files": [], "status": ImplementationStatus.paper_only},
    {"id": "code_flbeeline", "asset_type": AssetType.local_archive, "title": "FLBeeline 源码包", "local_path": "软件学报1—code.zip", "external_url": None, "default_branch": None, "key_files": ["code1/defenses.py", "code1/server.py", "code1/client.py", "code1/utils/utils.py", "code1/main-single.py"], "status": ImplementationStatus.local_archive},
    {"id": "repo_feature_poison", "asset_type": AssetType.external_code, "title": "bo-lab520/FeaturePoisonAttack", "local_path": None, "external_url": "https://github.com/bo-lab520/FeaturePoisonAttack", "default_branch": "main", "key_files": ["exps/federated_main.py", "lib/update.py", "lib/utils.py", "lib/sampling.py", "exps/conf.json"], "status": ImplementationStatus.external_code},
    {"id": "repo_fedulip", "asset_type": AssetType.external_code, "title": "zjx2024/fedulip_icml", "local_path": None, "external_url": "https://github.com/zjx2024/fedulip_icml", "default_branch": "main", "key_files": ["base2new/fedulip_base2new.py", "cross_dataset/fedulip_cross_dataset.py", "domain_abcd/fedulip_domain_abcd.py", "single_dataset/fedulip_single_dataset.py", "ULIP/models/fedulip.py"], "status": ImplementationStatus.external_code},
    {"id": "code_fed_ref", "asset_type": AssetType.local_archive, "title": "FedRef 联邦学习参考代码", "local_path": None, "external_url": None, "default_branch": None, "key_files": ["utils_methods.py", "utils_methods_FedCADS.py", "utils_models.py", "utils_dataset.py", "example_code_cifar10.py"], "status": ImplementationStatus.local_archive},
]


DATASETS = [
    {"id": "cifar10", "name": "CIFAR-10", "task_type": "vision_classification", "split_options": ["iid", "dirichlet", "pathological"], "description": "10 类彩色图像分类基准数据集。"},
    {"id": "cifar100", "name": "CIFAR-100", "task_type": "vision_classification", "split_options": ["iid", "dirichlet", "pathological"], "description": "100 类彩色图像分类基准数据集。"},
    {"id": "mnist", "name": "MNIST", "task_type": "vision_classification", "split_options": ["iid", "dirichlet", "pathological"], "description": "手写数字识别基准数据集。"},
    {"id": "tiny_imagenet", "name": "Tiny-ImageNet", "task_type": "vision_classification", "split_options": ["dirichlet"], "description": "FedCVC/GFed-HSAM 对比覆盖的 200 类小型 ImageNet 子集。"},
    {"id": "fashion_mnist", "name": "FashionMNIST", "task_type": "vision_classification", "split_options": ["dirichlet"], "description": "FLBeeline 论文覆盖的服饰图像分类数据集。"},
    {"id": "emnist", "name": "EMNIST", "task_type": "vision_classification", "split_options": ["dirichlet"], "description": "FLBeeline 论文覆盖的扩展手写字符数据集。"},
    {"id": "femnist", "name": "FEMNIST", "task_type": "vision_classification", "split_options": ["dirichlet"], "description": "FLDetector 论文覆盖的联邦手写字符数据集。"},
    {"id": "ag_news", "name": "AG News", "task_type": "text_classification", "split_options": ["dirichlet"], "description": "FedCVC/FLBeeline 参考论文覆盖的新闻文本分类基准数据集。"},
    {"id": "market1501", "name": "Market1501", "task_type": "reid", "split_options": ["domain_as_client"], "description": "行人重识别基准数据集，多摄像头场景。"},
    {"id": "cuhk02", "name": "CUHK02", "task_type": "reid", "split_options": ["domain_as_client"], "description": "CO-EVO 论文覆盖的行人重识别数据集。"},
    {"id": "msmt17", "name": "MSMT17", "task_type": "reid", "split_options": ["domain_as_client"], "description": "CO-EVO 论文覆盖的跨摄像头行人重识别数据集。"},
    {"id": "cuhk03", "name": "CUHK03", "task_type": "reid", "split_options": ["domain_as_client"], "description": "CO-EVO 论文覆盖的行人重识别数据集。"},
    {"id": "modelnet40", "name": "ModelNet40", "task_type": "ulip3d", "split_options": ["iid"], "description": "40 类 3D 点云分类基准数据集。"},
    {"id": "scanobjectnn", "name": "ScanObjectNN", "task_type": "ulip3d", "split_options": ["iid"], "description": "FedULIP/ULIP 论文覆盖的真实扫描 3D 物体数据集。"},
    {"id": "shapenetcore", "name": "ShapeNetCore", "task_type": "ulip3d", "split_options": ["iid"], "description": "FedULIP cross-dataset 协议覆盖的 3D 形状数据集。"},
    {"id": "mvtec3d", "name": "MVTec3D", "task_type": "ulip3d", "split_options": ["iid"], "description": "FedULIP cross-dataset 协议覆盖的 3D 工业异常/物体数据集。"},
    {"id": "mnist3d", "name": "MNIST3D", "task_type": "ulip3d", "split_options": ["iid"], "description": "FedULIP cross-dataset 协议覆盖的 3D 数字数据集。"},
    {"id": "3dimage", "name": "3Dimage", "task_type": "ulip3d", "split_options": ["iid"], "description": "FedULIP cross-dataset 协议覆盖的 3D 图像派生数据集。"},
]


# Many-to-many relationships
MODULE_ALGORITHMS = [
    # core_engine
    ("core_engine", "fedavg", "primary"),
    ("core_engine", "fedprox", "primary"),
    ("core_engine", "scaffold", "primary"),
    ("core_engine", "feddyn", "primary"),
    ("core_engine", "fednova", "primary"),
    ("core_engine", "fedadam", "primary"),
    ("core_engine", "fedyogi", "primary"),
    ("core_engine", "fedbn", "primary"),
    ("core_engine", "ditto", "primary"),
    ("core_engine", "pfedme", "primary"),
    ("core_engine", "fedproto", "primary"),
    ("core_engine", "feddf", "primary"),
    ("core_engine", "fedkd", "primary"),
    # participation_adaptation
    ("participation_adaptation", "fedcvc", "primary"),
    ("participation_adaptation", "feddtc", "primary"),
    ("participation_adaptation", "rfl_nlcp", "primary"),
    ("participation_adaptation", "fedavg", "baseline"),
    ("participation_adaptation", "fedprox", "baseline"),
    ("participation_adaptation", "scaffold", "baseline"),
    ("participation_adaptation", "feddyn", "baseline"),
    ("participation_adaptation", "a_fedpd", "baseline"),
    ("participation_adaptation", "feddc", "baseline"),
    ("participation_adaptation", "fedvra", "baseline"),
    ("participation_adaptation", "fedvarp", "baseline"),
    ("participation_adaptation", "fedspeed", "baseline"),
    ("participation_adaptation", "fedsmoo", "baseline"),
    ("participation_adaptation", "fedtoga", "baseline"),
    ("participation_adaptation", "gfed_hsam", "baseline"),
    # optimization_control
    ("optimization_control", "gfed_hsam", "primary"),
    ("optimization_control", "sam", "primary"),
    ("optimization_control", "esam", "primary"),
    ("optimization_control", "hsam", "primary"),
    ("optimization_control", "fedavg", "baseline"),
    ("optimization_control", "feddyn", "baseline"),
    ("optimization_control", "fedprox", "baseline"),
    ("optimization_control", "scaffold", "baseline"),
    ("optimization_control", "a_fedpd", "baseline"),
    ("optimization_control", "fedspeed", "baseline"),
    ("optimization_control", "fedsmoo", "baseline"),
    ("optimization_control", "fedlesam_d", "baseline"),
    ("optimization_control", "a_fedpdsam", "baseline"),
    ("optimization_control", "fedgloss", "baseline"),
    ("optimization_control", "fedvra", "baseline"),
    ("optimization_control", "fedvarp", "baseline"),
    ("optimization_control", "fedtoga", "baseline"),
    # distillation_alignment
    ("distillation_alignment", "fedcads", "primary"),
    ("distillation_alignment", "fedavg", "baseline"),
    ("distillation_alignment", "feddyn", "baseline"),
    ("distillation_alignment", "scaffold", "baseline"),
    ("distillation_alignment", "feddc", "baseline"),
    ("distillation_alignment", "fedvra", "baseline"),
    ("distillation_alignment", "fedgkd_p", "baseline"),
    ("distillation_alignment", "a_fedpd", "baseline"),
    ("distillation_alignment", "fedfld", "baseline"),
    ("distillation_alignment", "feddf", "baseline"),
    ("distillation_alignment", "fedkd", "baseline"),
    # robust_aggregation
    ("robust_aggregation", "vert", "primary"),
    ("robust_aggregation", "krum", "primary"),
    ("robust_aggregation", "median", "primary"),
    ("robust_aggregation", "trimmed_mean", "primary"),
    ("robust_aggregation", "fldetector", "primary"),
    ("robust_aggregation", "fedavg", "baseline"),
    ("robust_aggregation", "fltrust", "baseline"),
    ("robust_aggregation", "flame", "baseline"),
    ("robust_aggregation", "multi_krum", "baseline"),
    # trust_screening
    ("trust_screening", "flbeeline", "primary"),
    ("trust_screening", "fedavg", "baseline"),
    ("trust_screening", "krum", "baseline"),
    ("trust_screening", "multi_krum", "baseline"),
    ("trust_screening", "median", "baseline"),
    ("trust_screening", "flame", "baseline"),
    ("trust_screening", "fltrust", "baseline"),
    # representation_attack
    ("representation_attack", "featurepoison", "primary"),
    ("representation_attack", "fedproto_prototype_attack", "primary"),
    # vision_benchmark
    ("vision_benchmark", "fedavg", "primary"),
    ("vision_benchmark", "feddyn", "primary"),
    ("vision_benchmark", "rfl_nlcp", "primary"),
    ("vision_benchmark", "fedcvc", "primary"),
    ("vision_benchmark", "feddtc", "primary"),
    ("vision_benchmark", "fedcads", "primary"),
    ("vision_benchmark", "gfed_hsam", "primary"),
    ("vision_benchmark", "fedprox", "baseline"),
    ("vision_benchmark", "scaffold", "baseline"),
    ("vision_benchmark", "fednova", "baseline"),
    ("vision_benchmark", "fedadam", "baseline"),
    ("vision_benchmark", "fedyogi", "baseline"),
    ("vision_benchmark", "fedbn", "baseline"),
    ("vision_benchmark", "ditto", "baseline"),
    ("vision_benchmark", "pfedme", "baseline"),
    ("vision_benchmark", "fedproto", "baseline"),
    ("vision_benchmark", "feddf", "baseline"),
    ("vision_benchmark", "fedkd", "baseline"),
    ("vision_benchmark", "feddc", "baseline"),
    ("vision_benchmark", "fedvra", "baseline"),
    ("vision_benchmark", "fedvarp", "baseline"),
    ("vision_benchmark", "fedgkd_p", "baseline"),
    ("vision_benchmark", "a_fedpd", "baseline"),
    ("vision_benchmark", "fedfld", "baseline"),
    ("vision_benchmark", "fedspeed", "baseline"),
    ("vision_benchmark", "fedsmoo", "baseline"),
    ("vision_benchmark", "fedtoga", "baseline"),
    # reid_generalization
    ("reid_generalization", "co_evo", "primary"),
    ("reid_generalization", "fedbn", "baseline"),
    ("reid_generalization", "ditto", "baseline"),
    ("reid_generalization", "pfedme", "baseline"),
    ("reid_generalization", "fedproto", "baseline"),
    ("reid_generalization", "scaffold", "baseline"),
    ("reid_generalization", "moon", "baseline"),
    ("reid_generalization", "fedprox", "baseline"),
    ("reid_generalization", "mixstyle", "baseline"),
    ("reid_generalization", "crossstyle", "baseline"),
    ("reid_generalization", "fedreid", "baseline"),
    ("reid_generalization", "fedpav", "baseline"),
    ("reid_generalization", "snr", "baseline"),
    ("reid_generalization", "dacs", "baseline"),
    ("reid_generalization", "sscu", "baseline"),
    # multimodal_3d
    ("multimodal_3d", "fedulip", "primary"),
    ("multimodal_3d", "fedavg", "baseline"),
    ("multimodal_3d", "ulip", "baseline"),
    ("multimodal_3d", "pointclip", "baseline"),
    ("multimodal_3d", "fedkgcoop", "baseline"),
    ("multimodal_3d", "fedvpt", "baseline"),
    ("multimodal_3d", "fedtpg", "baseline"),
    ("multimodal_3d", "fedcocoop", "baseline"),
    ("multimodal_3d", "fedmaple", "baseline"),
    ("multimodal_3d", "fedclip", "baseline"),
    ("multimodal_3d", "fedmvp", "baseline"),
]


MODULE_REFERENCES = [
    ("core_engine", "paper_fedavg", "paper"),
    ("core_engine", "paper_fednova", "paper"),
    ("core_engine", "paper_fedopt", "paper"),
    ("core_engine", "paper_fedbn", "paper"),
    ("core_engine", "paper_ditto", "paper"),
    ("core_engine", "paper_pfedme", "paper"),
    ("core_engine", "paper_fedproto", "paper"),
    ("core_engine", "paper_feddf", "paper"),
    ("core_engine", "paper_fedkd", "paper"),
    ("core_engine", "paper_rfl_nlcp", "paper"),
    ("core_engine", "paper_fedcads", "paper"),
    ("participation_adaptation", "paper_fedcvc_2026", "paper"),
    ("participation_adaptation", "paper_feddtc", "paper"),
    ("participation_adaptation", "paper_rfl_nlcp", "paper"),
    ("optimization_control", "paper_gfed_hsam", "paper"),
    ("optimization_control", "paper_sam", "paper"),
    ("optimization_control", "paper_esam", "paper"),
    ("optimization_control", "paper_fedcvc_2026", "paper"),
    ("distillation_alignment", "paper_fedcads", "paper"),
    ("robust_aggregation", "paper_vert", "paper"),
    ("robust_aggregation", "paper_krum", "paper"),
    ("robust_aggregation", "paper_median", "paper"),
    ("robust_aggregation", "paper_fldetector", "paper"),
    ("robust_aggregation", "paper_flbeeline", "paper"),
    ("trust_screening", "paper_flbeeline", "paper"),
    ("trust_screening", "code_flbeeline", "code"),
    ("representation_attack", "repo_feature_poison", "code"),
    ("vision_benchmark", "paper_fedavg", "paper"),
    ("vision_benchmark", "paper_fednova", "paper"),
    ("vision_benchmark", "paper_fedopt", "paper"),
    ("vision_benchmark", "paper_fedbn", "paper"),
    ("vision_benchmark", "paper_ditto", "paper"),
    ("vision_benchmark", "paper_pfedme", "paper"),
    ("vision_benchmark", "paper_fedproto", "paper"),
    ("vision_benchmark", "paper_feddf", "paper"),
    ("vision_benchmark", "paper_fedkd", "paper"),
    ("vision_benchmark", "code_fed_ref", "code"),
    ("reid_generalization", "paper_co_evo", "paper"),
    ("multimodal_3d", "repo_fedulip", "code"),
    ("multimodal_3d", "paper_fedulip", "paper"),
    ("multimodal_3d", "paper_ulip", "paper"),
    ("experiment_toolkit", "code_fed_ref", "code"),
]


ALGORITHM_REFERENCES = [
    ("fedavg", "paper_fedavg", "paper"),
    ("fednova", "paper_fednova", "paper"),
    ("fedadam", "paper_fedopt", "paper"),
    ("fedyogi", "paper_fedopt", "paper"),
    ("fedbn", "paper_fedbn", "paper"),
    ("ditto", "paper_ditto", "paper"),
    ("pfedme", "paper_pfedme", "paper"),
    ("fedproto", "paper_fedproto", "paper"),
    ("feddf", "paper_feddf", "paper"),
    ("fedkd", "paper_fedkd", "paper"),
    ("fedcvc", "paper_fedcvc_2026", "paper"),
    ("fedcads", "paper_fedcads", "paper"),
    ("rfl_nlcp", "paper_rfl_nlcp", "paper"),
    ("gfed_hsam", "paper_gfed_hsam", "paper"),
    ("feddtc", "paper_feddtc", "paper"),
    ("a_fedpd", "paper_fedcvc_2026", "paper"),
    ("a_fedpd", "paper_fedcads", "paper"),
    ("a_fedpdsam", "paper_fedcvc_2026", "paper"),
    ("fedspeed", "paper_fedcvc_2026", "paper"),
    ("fedspeed", "paper_rfl_nlcp", "paper"),
    ("fedsmoo", "paper_fedcvc_2026", "paper"),
    ("fedsmoo", "paper_rfl_nlcp", "paper"),
    ("fedlesam_d", "paper_fedcvc_2026", "paper"),
    ("fedgloss", "paper_fedcvc_2026", "paper"),
    ("feddc", "paper_fedcads", "paper"),
    ("feddc", "paper_rfl_nlcp", "paper"),
    ("fedvra", "paper_fedcads", "paper"),
    ("fedvra", "paper_rfl_nlcp", "paper"),
    ("fedvarp", "paper_rfl_nlcp", "paper"),
    ("fedtoga", "paper_rfl_nlcp", "paper"),
    ("fedgkd_p", "paper_fedcads", "paper"),
    ("fedfld", "paper_fedcads", "paper"),
    ("sam", "paper_sam", "paper"),
    ("esam", "paper_esam", "paper"),
    ("vert", "paper_vert", "paper"),
    ("krum", "paper_krum", "paper"),
    ("median", "paper_median", "paper"),
    ("trimmed_mean", "paper_median", "paper"),
    ("fldetector", "paper_fldetector", "paper"),
    ("flbeeline", "paper_flbeeline", "paper"),
    ("flbeeline", "code_flbeeline", "code"),
    ("multi_krum", "paper_krum", "paper"),
    ("multi_krum", "paper_flbeeline", "paper"),
    ("fltrust", "paper_fldetector", "paper"),
    ("fltrust", "paper_flbeeline", "paper"),
    ("flame", "paper_flbeeline", "paper"),
    ("featurepoison", "repo_feature_poison", "code"),
    ("fedproto_prototype_attack", "repo_feature_poison", "code"),
    ("co_evo", "paper_co_evo", "paper"),
    ("moon", "paper_co_evo", "paper"),
    ("mixstyle", "paper_co_evo", "paper"),
    ("crossstyle", "paper_co_evo", "paper"),
    ("fedreid", "paper_co_evo", "paper"),
    ("fedpav", "paper_co_evo", "paper"),
    ("snr", "paper_co_evo", "paper"),
    ("dacs", "paper_co_evo", "paper"),
    ("sscu", "paper_co_evo", "paper"),
    ("fedulip", "repo_fedulip", "code"),
    ("fedulip", "paper_fedulip", "paper"),
    ("fedulip", "paper_ulip", "paper"),
    ("ulip", "paper_ulip", "paper"),
    ("pointclip", "paper_fedulip", "paper"),
    ("fedkgcoop", "paper_fedulip", "paper"),
    ("fedvpt", "paper_fedulip", "paper"),
    ("fedtpg", "paper_fedulip", "paper"),
    ("fedcocoop", "paper_fedulip", "paper"),
    ("fedmaple", "paper_fedulip", "paper"),
    ("fedclip", "paper_fedulip", "paper"),
    ("fedmvp", "paper_fedulip", "paper"),
]

SMOKE_VALIDATED_ALGORITHM_IDS = {algorithm["id"] for algorithm in ALGORITHMS}
EXECUTABLE_MODULE_IDS = {
    "core_engine",
    "participation_adaptation",
    "optimization_control",
    "distillation_alignment",
    "trust_screening",
    "robust_aggregation",
    "representation_attack",
    "vision_benchmark",
    "reid_generalization",
    "multimodal_3d",
    "experiment_toolkit",
}

for algorithm in ALGORITHMS:
    if algorithm["id"] in SMOKE_VALIDATED_ALGORITHM_IDS:
        algorithm["status"] = ImplementationStatus.validated

for module in MODULES:
    if module["id"] in EXECUTABLE_MODULE_IDS:
        module["status"] = ImplementationStatus.implemented
        module.setdefault("meta_json", {})["implementation_status"] = "implemented"


SEED_DATA = {
    "modules": MODULES,
    "algorithms": ALGORITHMS,
    "references": REFERENCES,
    "datasets": DATASETS,
    "module_algorithms": MODULE_ALGORITHMS,
    "module_references": MODULE_REFERENCES,
    "algorithm_references": ALGORITHM_REFERENCES,
}
